// Generated by CoffeeScript 1.6.1

/*
Helper to show easier to read exceptions
*/


(function() {

  module.exports.death = function(msg) {
    throw msg;
  };

  module.exports.homeDir = function() {
    return process.env[(process.platform === 'win32' ? 'USERPROFILE' : 'HOME')];
  };

}).call(this);
