// Generated by CoffeeScript 1.3.3

/*
Helper to show easier to read exceptions
*/


(function() {

  module.exports.death = function(msg) {
    sugar.error(("Blender: " + msg).red);
    throw '--';
  };

}).call(this);
